import Image from "next/image";
import Head from 'next/head';
import Logo from "../assets/logo.png";
import EmailLogo from "../assets/o-email.png";
import PasswordLogo from "../assets/senha.png";
import styles from "../styles/home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <div className={styles.login}>
            <Image src={Logo} alt="Logo da Delicie" width={150} height={150} style={{marginBottom: "20px"}}/>
            <label className={styles.label}>Email</label>
            <input type="email" className={styles.input} />
            <div className={styles.icon}>
              <Image src={EmailLogo} alt="Icone de email" width={20} height={20} />
            </div>
            <label className={styles.label}>Senha</label>
            <input type="password" className={styles.input} />
            <div className={styles.icon}>
              <Image src={PasswordLogo} alt="Icone de senha" width={20} height={20} />
            </div>
            <button className={styles.button}>Entrar</button>
          </div>
        </div>
      </main>
    </>
  );
};
